In [16]:
import numpy as np

In [17]:
nums=[4.50,4.75,4.91,5.34,5.80,7.05,7.90,8.23,8.70,9.00]

In [18]:
res=[]

In [19]:
def RegressionTree(nums, max_depth=2):
    nums.sort()
    nums=np.array(nums)
    nums=nums.reshape(-1,1)
    from sklearn.tree import DecisionTreeRegressor
    tree_reg=DecisionTreeRegressor(max_depth=max_depth)
    tree_reg.fit(nums,nums)
    return tree_reg.predict(nums)

In [20]:
for i in range(4):
    res.append(RegressionTree(nums, max_depth=i+1))
res

[array([5.06 , 5.06 , 5.06 , 5.06 , 5.06 , 8.176, 8.176, 8.176, 8.176,
        8.176]),
 array([4.72      , 4.72      , 4.72      , 5.57      , 5.57      ,
        7.475     , 7.475     , 8.64333333, 8.64333333, 8.64333333]),
 array([4.5 , 4.83, 4.83, 5.34, 5.8 , 7.05, 7.9 , 8.23, 8.85, 8.85]),
 array([4.5 , 4.75, 4.91, 5.34, 5.8 , 7.05, 7.9 , 8.23, 8.7 , 9.  ])]

In [21]:
segs=[]
for fla in res:
    seg=[]
    i=0
    while i < len(fla) - 1:
        if(fla[i]!=fla[i+1]):
            seg.append(i+1)
        i+=1
    segs.append(seg)
segs

[[5], [3, 5, 7], [1, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8, 9]]